services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yaks2005
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongodb-keyfile:/etc/mongodb-keyfile:ro
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongodb-keyfile"
      ]

volumes:
  mongo_data: